apiVersion: apps/v1 
kind: Deployment
metadata:
  name: ui-deployment 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: consensusclubs/ui-consensus-clubs:v1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "npm run build && NODE_ENV=production node server.js" ]
